name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup multiarch build environment
      run: docker buildx create --name mutliarch-builder --use --bootstrap
    - name: Log in to ghcr.io registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build multiarch Docker image and push to ghcr.io
      run: docker buildx build . --push --file Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7 --tag ghcr.io/jungin500/axfree-smi2srt:$(date +%Y%m%d)
    - name: Log in to docker.io registry
      run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login docker.io -u jungin500 --password-stdin
    - name: Build cached docker image and push to docker.io
      run: docker buildx build . --push --file Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7 --tag docker.io/jungin500/axfree-smi2srt:latest
