name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup multiarch build environment
      run: docker buildx create --name mutliarch-builder --use --bootstrap
    - name: Build multiarch Docker image
      run: docker buildx build . --file Dockerfile --platform linux/amd64,linux/arm64,linux/arm/v7 --tag ghcr.io/jungin500/axfree-smi2srt:$(date +%Y%m%d)
